### ISSUE TITLE
Docker container crashed

### ISSUE THREAD

**Issue by coolpalani** [c4po/harbor_exporter#1]
Hi,

I tried to run the service as docker but it's throwing below error message and docker dead while hit ipaddress:9107

`level=info ts=2020-02-13T08:35:01.260Z caller=harbor_exporter.go:261 msg="Starting harbor_exporter" version="(version=v0.2, branch=master,` `revision=70e0d756ff79908745b4395439df31cb57c1f7eb)"`
`level=info ts=2020-02-13T08:35:01.260Z caller=harbor_exporter.go:262` `build_context="(go=go1.13.7, user=root, date=2020-02-13-07:48:34-UTC)"`
`level=info ts=2020-02-13T08:35:01.327Z caller=harbor_exporter.go:304 msg="Listening on` `address" address=:9107`

`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x877144]`
`goroutine 39 [running]:`
`main.HarborClient.request(0xc00018c570, 0x7ffe685d2f21, 0x1c, 0xc000022030, 0xe, 0xc000022050,` `0xa, 0x1dcd6500, 0x0, 0xa48680, ...)`
        `/src/harbor_exporter.go:146 +0x3a4`
`main.(*Exporter).collectScanMetric(0xc0000a18c0, 0xc000104060, 0xc0003aaea8)`
        `/src/metrics_scan.go:19 +0xac`
`main.(*Exporter).Collect(0xc0000a18c0, 0xc000104060)`
        `/src/harbor_exporter.go:221 +0x3c`
`github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()`
        `/go/pkg/mod/github.com/prometheus/client_golang@v1.4.0/prometheus/registry.go:443 +0x19d`
`created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather`
        `/go/pkg/mod/github.com/prometheus/client_golang@v1.4.0/prometheus/registry.go:454 +0x57d`

**Comment by c4po** [comment]
@coolpalani  from the log it seems you don't have right connection to your harbor server.
Can you try if you can run this curl command with your harbor server.
`curl -u ${HARBOR_USERNAME}:${HARBOR_PASSWORD} ${HARBOR_SERVER}/api/logs`

**Comment by cmur2** [comment]
I experience the same segfault and checked using curl which gives:
```
$ curl -u admin https://server/api/scans/all/metrics
Enter host password for user 'admin':
{"code":503,"message":"no scanner is configured, it's not possible to scan"}
```

Looking at the source code in https://github.com/c4po/harbor_exporter/blob/master/harbor_exporter.go#L221 the first thing that is retrieved is container scanner statistics but my Harbor instance does not have a scanner.

@c4po I'm really grateful that you developed this exporter where the official software did nothing in 2 year to implement metrics! 
I wonder though why a software crashes with a segmentation fault when it retrieved a wrong parameter - shouldn't line https://github.com/c4po/harbor_exporter/blob/master/harbor_exporter.go#L146 log an error message instead?

Edit: I'm using the official `c4po/harbor-exporter:v0.2` image.

**Comment by cmur2** [comment]
Looking at https://github.com/c4po/harbor_exporter/blob/master/harbor_exporter.go#L145 it becomes obvious that `err == nil` when `resp.StatusCode != http.StatusOK` which leads to the segfault in the next line where `err.Error()` is done but `err == nil`.
