### ISSUE TITLE
Add possibility to collect only specific metrics

### ISSUE THREAD

**Issue by mdraijer** [c4po/harbor_exporter#11]
I noticed that harbor_exporter makes Harbor use significantly more resources when harbor_exporter is running. A few times the harbor-core container ended up in a CrashLoopBackOff. Adding more resources might help, increasing the interval in the servicemonitor also helps, but in the end that's just attacking symptoms.
The root cause, of course, it that the harbor_exporter is sending a burst of API calls on every interval. Would the metrics be built into Harbor then you don't need the overhead of API calls, you could make the collection of the metrics more efficient and you could spread that collection of metrics over time. But well, there have been many requests for metrics in Harbor over almost 3 years and no one's building it...

So, some suggestions to improve harbor_exporter until Harbor exposes metrics itself:
1) Add configuration options to enable or disable certain collectors. Then you can run the exporter for just the metrics you're interested in. Or you can run multiple instances of the exporter, each with a subset of the metrics and make separate servicemonitors for each exporter.
2) Add query parameters to the /metrics endpoint so the servicemonitor can specify which metrics it wants. Then you can run only one exporter and define multiple servicemonitors. For example one that retrieves quota metrics every 30 sec (because you might need that often and it uses almost no resources in Harbor) and one that retrieves repository metrics (tags, pulls, stars) every 10 minutes (because you need that data, but know that it requires significant resources from your Harbor).

Option 2 seems the best option but for option 1 I know how I can implement it myself. And there might be better options still.

Interested to hear your opinion!

**Comment by c4po** [comment]
Hi @mdraijer, How bad does the harbor_exportor impact to the harbor performance?  What's your harbor server resource allocation and how frequent do you get the exception.  Just want to know if this is a big issue in most use cases. 

I was thinking to modify the `func (h HarborClient) request` in `harbor_exporter.go` to reuse the http connection for each metric requests. Not sure if that will help reduce the pressure on harbor server.

**Comment by mdraijer** [comment]
Under normal circumstances the Harbor instance where we experienced the crash, component harbor-core, has peaks of 0.15 CPU in use. (It has regular peaks in usage every few minutes because of replication schedules which are running.) The pattern is really stable: every few minutes rising from almost 0 to 0.15 and then back to almost 0.

When I first started the harbor-exporter, and deployed a servicemonitor with interval 30 seconds, it changed to having peaks of 0.55 CPU, and a minimum inbetween of 0.40.
Then I changed the interval to 55 seconds and the CPU usage ranged between 0.25 and 0.40 CPU.
Every time that I stopped harbor-exporter it dropped back to the original values.
With a branched version of harbor-exporter, where I can disable metrics, I have a constant usage of approximately 0.08 to 0.18 CPU.

Of course it is possible to increase the resource requests/limits but this really seems bad usage of resources.

I tested by changing the code to eliminate one metrics collector at a time and found that repositories was the main culprit (I think more than two-thirds of the total).
Maybe reusing the http connection helps, but I think the main problem is in the implementation of the API calls in Harbor itself. They might not be designed for continuous requests.

Some background: we have currently 27 projects with 345 repositories in the Harbor where I have the data from.

**Comment by c4po** [comment]
thank for the detail analysis. from your suggestions.
> 1. Add configuration options to enable or disable certain collectors. 
It's easy to implement, but may be hard to maintain the configuration in future if we have many metrics to export.
>2. Add query parameters to the /metrics endpoint.
you mean we need create a "prometheus job" for each metrics? and using different scrape interval?

how about we change the exporter to only call the expensive harbor api every 10 scraps? 

I don't want to give end user too many freedom and options to config and run this harbor_exporter. This should be a simple tool and just need get install to run. I would rather hard code the configuration which works for most users instead of let end user to learn how to config it in their environment.

**Comment by mdraijer** [comment]
Totally agree with 'it should run out of the box'. Indeed the tool should do be configured optimally in advance. However, it should be _possible_ for users to tweak that behaviour. Of course within reasonable limits so the code does not get too complex.

I agree that option 1 might make the code less maintainable. I saw that while implementing it [here](https://github.com/mdraijer/harbor_exporter/tree/feature/skip-metrics). Would be nice to have one list of collector names in the code and from that dynamically define and call the collectors and build the help text and what not. But I'm not that proficient in Go.
I still implemented the skip option in my branch because I simply _need_ the functionality. By the way: this option is also convenient in order to make the exporter Harbor 1.9-compatible: I use 1.9 and that version does not have the scan api yet, so now I can prevent a lot of errors in the logs...

For option 2: I suppose by 'prometheus job' you mean what I refer to as a service monitor. The query parameters could be designed such that you can specify a set of metrics to be collected. Possibly same as in my branch: comma separated list of collector names. What I would do if that were implemented: define 2 service monitors, 1 for repositories (maybe every 10 min) and 1 for all the rest (maybe every 30 sec).
So: no, not one for each metrics.

As for option 3: Could work.
The metrics collected in scrape 1 need to be returned also (same values) in scrapes 2-10, because otherwise you get missing values. This also means that you might get stale data for those metrics in scrapes 2-10 and have to wait for scrape 11 to get new data.
But that's not per se a problem: metrics are supposed to give you an idea of trends, not exact data (at least: for many metrics the exactness is not an issue).
I would prefer to give the user the _option_ to tweak this number (10) so they can choose to have it on every scrape, or rather less often.

Where I do see a possible problem is that in this scenario scrape 1 will still have a burst of API calls. But that problem is also not solved by options 1 and 2. What option 3 adds is the possibility to implement it such that on every scrape _part_ of the projects is updated as for the repositories metrics.
Might be too fancy, but we could compute (# of projects to scrape repo metrics from) = (# of projects) / (repo collector scrape interval), where this interval is default 10 but configurable.
Each scrape we go over (# of projects to scrape repo metrics from) and only for _those_ get new repositories data. Then after each round of 10 scrapes you have the data for each repository refreshed.
Of course projects can be added, removed and renamed, and you have to compare that to the list of projects you have in memory, so there's quite some complexity in there.

For now I stick with my version that skips the repositories metrics completely. Hope we can find a solution that works and is maintainable.

**Comment by c4po** [comment]
to reduce the number of api call to harbor from the exporter, we can just change the `scape_interval` to a big number. https://github.com/c4po/harbor_exporter/blob/master/kubernetes/harbor-exporter.yaml#L117
can you change that value to `30s` to see if it can solve your problem?

**Comment by mdraijer** [comment]
That interval is the one I meant where I wrote 30 sec and 55 sec. So I had already started of with 30 sec, so it doesn't solve my problem.

**Comment by mdraijer** [comment]
We've been using the version from https://github.com/mdraijer/harbor_exporter/tree/feature/skip-metrics for quite some time now without any problems. It is absolutely not possible to work _without_ the option to skip metrics, so we will do futher development on that fork only.

**Comment by c4po** [comment]
Ok, I'll take a look at your implementation and merge this feature back

**Comment by c4po** [comment]
I have just released the v0.5.2 with additional command line flag `--skip.metrics`

**Comment by mdraijer** [comment]
Great, thanks!!
