### ISSUE TITLE
unsupported protocol scheme \"\"", using the yaml for a kubernetes cluster.

### ISSUE THREAD

**Issue by cleman95** [c4po/harbor_exporter#12]
Hello,

**overview:**

I'm trying to export some metrics from Harbor to prometheus. I deployed Harbor using the Helm Chart  on a Kubernetes cluster. So I used the yaml file given to deploy the harbor exporter on my kubernetes cluster. I only get two metrics related to harbor. The Harbor instance is configurated with HTTPS.

**Environment:** 

OS : Centos 7
Kubernetes version : 1.16.7
Chart Helm version : harbor-1.3.1
Harbor version: 1.10.1
Helm version: 2
Harbor-exporter: v0.3.1

**Expected Behavior:**

When deploying the yaml file for harbor exporter in the namespace where my harbor instance is located and changing every prefix in the yaml file, I should get all the metrics listed in the documentation of the harbor exporter.

**Actual behavior:**

I deploy the harbor exporter and i get some metrics about go and two metrics regarding harbor: harbor_harbor_up and harbor_exporter_build_info. 

**Steps to reproduce the problem:**

First deploy Harbor using the Helm chart on a kubernetes cluster. Then change the prefix and the namespace in the yaml file of the harbor exporter and deploy it in the same namespace as the Harbor instance. Get the logs of the harbor-exporter pod. 

**Logs:**

```level=error ts=2020-04-16T10:10:51.200Z caller=metrics_quotas.go:35 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-04-16T10:10:51.200Z caller=harbor_exporter.go:105 msg="Error handling request for /api/systeminfo/volumes" err="Get harboor-harbor-core/api/systeminfo/volumes: unsupported protocol scheme \"\""
level=error ts=2020-04-16T10:10:51.200Z caller=metrics_systemvolumes.go:19 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-04-16T10:10:51.200Z caller=harbor_exporter.go:105 msg="Error handling request for /api/projects" err="Get harboor-harbor-core/api/projects: unsupported protocol scheme \"\""
level=error ts=2020-04-16T10:10:51.200Z caller=metrics_repositories.go:45 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-04-16T10:10:51.200Z caller=harbor_exporter.go:105 msg="Error handling request for /api/replication/policies" err="Get harboor-harbor-core/api/replication/policies: unsupported protocol scheme \"\""
level=error ts=2020-04-16T10:10:51.200Z caller=metrics_replications.go:30 msg="Error retrieving replication policies" err="unexpected end of JSON input"
```

**Comment by c4po** [comment]
@cleman95 
sorry the document is not clear, please update your `harbor_exporter.yaml` file to change the
```
            - name: HARBOR_URI
              value: prefix-harbor-core # change prefix to the name of your Helm release
```
to
```
            - name: HARBOR_URI
              value: http://prefix-harbor-core # change prefix to the name of your Helm release
```

**Comment by cleman95** [comment]
thanks a lot it worked for me. So i'm clossing this issue. Great Exporter thanks.
