### ISSUE TITLE
401 invalid credentials

### ISSUE THREAD

**Issue by WYmindsky** [c4po/harbor_exporter#16]
kubernets：1.14

**error：**
=error ts=2020-05-25T07:43:23.053Z caller=harbor_exporter.go:109 msg="Error handling request for /api/scans/all/metrics" http-statuscode="404 Not Found"
level=error ts=2020-05-25T07:43:23.053Z caller=metrics_scan.go:23 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-05-25T07:43:23.059Z caller=harbor_exporter.go:109 msg="Error handling request for /api/statistics" http-statuscode="401 Unauthorized"
level=error ts=2020-05-25T07:43:23.060Z caller=metrics_statistics.go:25 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-05-25T07:43:23.066Z caller=harbor_exporter.go:109 msg="Error handling request for /api/quotas" http-statuscode="401 Unauthorized"
level=error ts=2020-05-25T07:43:23.066Z caller=metrics_quotas.go:35 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-05-25T07:43:23.071Z caller=harbor_exporter.go:109 msg="Error handling request for /api/systeminfo/volumes" http-statuscode="401 Unauthorized"
level=error ts=2020-05-25T07:43:23.071Z caller=metrics_systemvolumes.go:19 unexpectedendofJSONinput=(MISSING)
level=error ts=2020-05-25T07:43:23.446Z caller=harbor_exporter.go:109 msg="Error handling request for /api/replication/policies" http-statuscode="401 Unauthorized"
level=error ts=2020-05-25T07:43:23.446Z caller=metrics_replications.go:30 msg="Error retrieving replication policies" err="unexpected end of JSON input"

user：admin
password is corect

help me please，tks

**Comment by c4po** [comment]
what's your harbor version?
harbor 2 support is still under developing

**Comment by WYmindsky** [comment]
@c4po 
harbor version: v1.9.2
harbor.server: https://hub.domain.io (inner service)
ssl cert: *.domain.io

**Comment by c4po** [comment]
can you test your connection with curl command
```
curl -X GET "https://hub.xforwardai.io/api/health" -H "accept: application/json" --user admin:password
```

**Comment by WYmindsky** [comment]
$ curl -X GET "https://hub.domain.io/api/health" -H "accept: application/json" --user admin:passwd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   498  100   498    0     0   3921      0 --:--:-- --:--:-- --:--:--  3921{
  "status": "healthy",
  "components": [
    {
      "name": "core",
      "status": "healthy"
    },
    {
      "name": "portal",
      "status": "healthy"
    },
    {
      "name": "jobservice",
      "status": "healthy"
    },
    {
      "name": "database",
      "status": "healthy"
    },
    {
      "name": "redis",
      "status": "healthy"
    },
    {
      "name": "registryctl",
      "status": "healthy"
    },
    {
      "name": "registry",
      "status": "healthy"
    }
  ]
}

**Comment by c4po** [comment]
is the exporter run in same kubernetes as the harbor? can you check the deployment yaml file?
