### ISSUE TITLE
Getting Error : unsupported protocol scheme

### ISSUE THREAD

**Issue by ghost** [c4po/harbor_exporter#17]
exporter version :  v0.3.1, branch=master (kubernetes)
harbor version : Version v1.10.1-f3e11715

`level=info ts=2020-05-26T15:32:03.751Z caller=harbor_exporter.go:300 msg="Starting harbor_exporter" version="(version=v0.3.1, branch=master, revision=5755c2d97a2fd5309fa883ad11aeea74bca24942)
level=info ts=2020-05-26T15:32:03.752Z caller=harbor_exporter.go:301 build_context="(go=go1.13.9, user=root, date=2020-04-03-14:14:06-UTC)"
level=info ts=2020-05-26T15:32:03.865Z caller=harbor_exporter.go:343 msg="Listening on address" address=:9107
level=error ts=2020-05-26T15:32:16.692Z caller=harbor_exporter.go:105 msg="Error handling request for /api/scans/all/metrics" err="Get registry-harbor-core/api/scans/all/metrics: unsupported protocol scheme \"\""`

**Comment by c4po** [comment]
@naren4b 
Can you check it's same as this one https://github.com/c4po/harbor_exporter/issues/12 ?

**Comment by naren4b** [comment]
Yes it works , This issue can be closed
