### ISSUE TITLE
harbor_exporter Monitoring cannot find some parameters 

### ISSUE THREAD

**Issue by txg1550759** [c4po/harbor_exporter#18]
harbor_exporter Monitoring cannot find some parameters of harbor version 1.8, such as harbor_ quotas_ size_ bytes ,harbor_ quotas_ count_ Total, etc,

In fact, only:

![image](https://user-images.githubusercontent.com/17263614/83841557-aa446080-a733-11ea-8879-f9a19a367600.png)

**Comment by c4po** [comment]
sorry, I don't have time to support Harbor API V1 anymore.
can you upgrade Harbor to V2+ and harbor_exporter to v0.5.0 +?
