### ISSUE TITLE
Question: What's the best way to deploy?

### ISSUE THREAD

**Issue by bjethwan** [c4po/harbor_exporter#21]
I have got a harbor cluster deployed outside of k8s.
I am running multiple harbor nodes fronted by a load balancer, using the same storage.

Should I be running this exporter within k8s or run it on each harbor node (as either a separate systemd unit or club it with harbor's docker-compose)? 

Kindly share some insights considering system availability and performance.

**Comment by c4po** [comment]
@bjethwan I don't have many experience to deploy harbor as cluster. the exporter can run as standalone docker container. If you have harbor server run in docker-compose, I guess it will be easy to add the exporter to the docker compose file.
if all your nodes are share the same storage, you can run exporter with one or all nodes. they should return same result.

**Comment by bjethwan** [comment]
@c4po 
Thanks Max. 
I had to deploy this within the k8s, as I get Prometheus auto-discovery. So it was easy.

Your exporter is working well.

I could not understand harbor_repositories_star metrics, as I don't see Star rating support in my harbor install v1.10.1. Kindly provide a one line description

**Comment by c4po** [comment]
yes, it seems Harbor removed the star feature. I'll remove the metrics.
