### ISSUE TITLE
only first page of harbor results are fetched

### ISSUE THREAD

**Issue by cjnosal** [c4po/harbor_exporter#29]
Harbor APIs are paginated. If the number of projects/repos/etc exceeds the default page size then not all metrics will be exported.

A quick fix might by to set an excessively large default page size (or expose as an environment variable) but that might have performance impacts. A more rigorous solution will need to loop over each page of results.

**Comment by c4po** [comment]
for metrics, I think have a large page size will make sense.
we will eventually loop all the pages for the metrics, why not just sending one request and fetch all?

**Comment by cjnosal** [comment]
It can be a tradeoff between latency for the exporter vs instantaneous load on harbor - I didn't want to make assumptions how harbor APIs scale when querying for increasingly large page sizes. I added a flag in my PR so the end user can choose - set a sufficiently large page and one request will fetch all, or leave the default harbor page size and let the exporter iterate if necessary.

**Comment by c4po** [comment]
@xtreme-conor-nosal  what's the harbor version you are on?
I tested the curl command on harbor core v2.0.2, it seems without providing pagesize, the default will return all records for projects. (at least 100+)

can you test the latest harbor_exporter release `v0.5.0` again and advise if this is still an issue.

**Comment by cjnosal** [comment]
We tested on Harbor 2.0.1. It looks like the default in Harbor is intended to be 500 (https://github.com/goharbor/harbor/blob/master/src/common/api/base.go#L32-L33). `git blame` shows that change dates back to 2016 though, so maybe they applied the default to more calls. In my 2.0.1 tests, `api/v2.0/projects` returns all our projects, but `api/v2.0/projects/$largeproject/repositories` only returns the first 10.

However, they also define a maximum of 500. If 2.0.2 returns 500 for calls that previously returned 10, that's an improvement, but not a complete fix. We currently reach ~100 projects and over 100 repos per project, and growing. 500 is large, but not unreachable. If the exporter doesn't paginate, we'll eventually need to re-open this issue.

**Comment by c4po** [comment]
It seems the harbor api return `x-total-count` in the response header.
I'll see how to use it to fetch all results

**Comment by c4po** [comment]
@xtreme-conor-nosal  let's move the conversation here.

> This PR could be adapted after rebasing (unless you have a separate effort in flight). Using the header would require request to return the response headers (or at least the count if present). Then the checks for len(data) == pageSize would become something like (page - 1) * pageSize + len(data) < x-total-count

I don't have any other big change in flight. for this one, I want to do a request first, get the data and header, then based on the header value, decide if we need go out of the loop. so it can save 1 HEAD call to the api
```
page=1
for {
projectBody, projectCount := request("/projects?page=",page)
...
if page * pagesize>=projectCount 
    break
page++
}
```

**Comment by badsmoke** [comment]
are there any news?
what is the best solution to implement it and when will it be implemented?

**Comment by cjnosal** [comment]
Sorry, I've been busy and haven't had the chance, but I have some time over the next few days. The best solution is to work off `x-total-count`.
