### ISSUE TITLE
harbor_repositories_tags_total metric is not working for Harbor 2

### ISSUE THREAD

**Issue by maxdanilov** [c4po/harbor_exporter#31]
After we've upgraded Harbor to v2.0.1 and harbor-exporter to v0.4.0, we found out the tag count metric `harbor_repositories_tags_total` is not working anymore (as it has been working with Harbor 1.x)

This metric is very useful with Harbor 2, since Harbor has dropped the native tag count support for Quotas, and without alerting using metrics from the exporter it's not possible get warned before a repository has blown up due to an extensive number of tags.

Since Harbor has shifted focus from tags to a more generic concept of artifacts, would it be possible to get metrics for the count of those per repo? They seem to be included in the response of `/api/v2.0/projects/<...>/repositories`

**Comment by c4po** [comment]
this should be fixed in `v0.5.0` now.
harbor v2 changed the name in structure.

however, the `repositories_star_total` is not supported anymore in harbor v2
