### ISSUE TITLE
Build Helm Chart for harbor-exporter

### ISSUE THREAD

**Issue by c4po** [c4po/harbor_exporter#37]
* build a helm chart
* create the installation document

* (bonus point), add to https://github.com/goharbor/harbor-helm

**Comment by dntosas** [comment]
@c4po i can help with that ^^ one question for the bonus point, is that afaik, harbor has on its roadmap to implement prometheus on its internal codebase. do you think it is worth trying add the exporter to their official helm chart also ?

**Comment by c4po** [comment]
@dntosas  I created the issue https://github.com/goharbor/harbor-helm/issues/707 . No sure if they will add the this exporter or wait for the official prometheus feature build in harbor.
