### ISSUE TITLE
How to debug the issue related to : "cannot get harbor api version" err="unable to determine harbor version"

### ISSUE THREAD

**Issue by naren4b** [c4po/harbor_exporter#38]
![image](https://user-images.githubusercontent.com/3488520/92296757-68ef6700-ef55-11ea-920f-68e63fc772fc.png)

```

level=info ts=2020-09-05T03:13:22.421Z caller=harbor_exporter.go:200 msg="check v1 with /api/systeminfo" err="Get https://myregistry.com/api/systeminfo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
level=info ts=2020-09-05T03:13:32.422Z caller=harbor_exporter.go:211 msg="check v2 with /api/v2.0/systeminfo" erro="Get https://myregistry.com/api/v2.0/systeminfo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
level=error ts=2020-09-05T03:13:32.422Z caller=harbor_exporter.go:305 msg="cannot get harbor api version" err="unable to determine harbor version"
level=info ts=2020-09-05T03:13:32.946Z caller=harbor_exporter.go:286 msg="Starting harbor_exporter" version="(version=v0.5.2, branch=master, revision=69bff757da5d6676ea42f06064e0fd4dc3ea3820)"
level=info ts=2020-09-05T03:13:32.946Z caller=harbor_exporter.go:287 build_context="(go=go1.13.15, user=root, date=2020-08-26-18:43:17-UTC)"

```

**Comment by c4po** [comment]
What's your harbor version?
can you manually test with this 2 URLs? 
`https://myregistry.com/api/systeminfo` and `https://myregistry.com/api/v2.0/systeminfo`

**Comment by Nick-Triller** [comment]
@NarendranathPanda The screenshot indicates there is some kind of networking problem between Harbor and the Exporter. I think it's unlikely the issue is caused by the exporter.

**Comment by naren4b** [comment]
> What's your harbor version?
> can you manually test with this 2 URLs?
> `https://myregistry.com/api/systeminfo` and `https://myregistry.com/api/v2.0/systeminfo`

https://registry.xyz.com/api/v2.0/systeminfo is getting me the 200 OK  , other one is https://registry.xyz.com/api/v2.0/systeminfo gets me 404

**Comment by c4po** [comment]
> > What's your harbor version?
> > can you manually test with this 2 URLs?
> > `https://myregistry.com/api/systeminfo` and `https://myregistry.com/api/v2.0/systeminfo`
> 
> https://registry.xyz.com/api/v2.0/systeminfo is getting me the 200 OK , other one is https://registry.xyz.com/api/v2.0/systeminfo gets me 404

Is there any firewall or network policy that block harbor_exporter connect to your harbor instance?
it seems the harbor_exporter can not connect to yout harbor instance.

**Comment by naren4b** [comment]
Looks like there was a netwrok policy which was blocking the acess . Thanks for the support closing the  issue
