### ISSUE TITLE
Exporter OOMKilled all the time

### ISSUE THREAD

**Issue by dntosas** [c4po/harbor_exporter#45]
Docker image tags tested: `debug` `latest` `v0.5.3` `v0.5.2`

Harbor version: `v2.1.0`

Memory Limits: `256Mi`

Pod is always restarting due to OOMKill after some time of scraping. Maybe there is a leak to be caught in here? No logs showing some error or something not normal.
![Screenshot from 2020-09-23 09-10-46](https://user-images.githubusercontent.com/15010919/93973503-f536c200-fd7c-11ea-9048-8911602777ec.png)

**Comment by c4po** [comment]
@dntosas  how large is your harbor repo?
number of projects
number of images
etc.

**Comment by cjnosal** [comment]
In local testing I'm also seeing memory climb. Haven't had a chance to try profiling but just by having the Mac Activity Monitor open and running the exporter against a local harbor with a couple projects/artifacts the memory usage increases a few hundred kB on every /metrics request. The problem exists at least as far back as 0.4.0 (e04c7f853dadba636fd49dc1500cb53bea87f2b9)

**Comment by cjnosal** [comment]
Or it might eventually be stabilizing at a higher memory usage. It's possible it's related to caching or garbage collection

**Comment by dntosas** [comment]
- 2 projects
- ~10000 images
- 300 repos

**Comment by c4po** [comment]
@dntosas can you increase the memory limit to see you still get OOM or the garbage collection will work.

**Comment by dntosas** [comment]
already done that ^^ exporter seems to stabilize at about ~2GB of memory

**Comment by Nick-Triller** [comment]
Please see [issue 52](https://github.com/c4po/harbor_exporter/issues/52) for a resolution. Harbor Exporter leaks TCP connections. These are closed after some time, this is the reason the used memory stabilizes at some point.
