### ISSUE TITLE
Duplicate values while scraping the metrics through Exporter

### ISSUE THREAD

**Issue by pruthvirajkanmantha** [c4po/harbor_exporter#5]
level=error ts=2020-03-17T13:58:20.891Z caller=harbor_exporter.go:111 msg="error gathering metrics:8 error(s) occurred:\n* collected metric "harbor_quotas_count_total" { label:<name:"repo_id" value:"0" > label:<name:"repo_name" value:"" > label:<name:"type" value:"hard" > gauge:<value:-1 > } was collected before with the same name and label values\n* collected metric "harbor_quotas_count_total" { label:<name:"repo_id" value:"0" > label:<name:"repo_name" value:"" > label:<name:"type" value:"used" > gauge:<value:0 > } was collected before with the same name and label values\n* collected metric

**Comment by c4po** [comment]
@Pruthvi08 is the exporter crash or just warning message? what's the harbor version you are using?

**Comment by pruthvirajkanmantha** [comment]
@c4po The exporter pod is still running but it throws the above mentioned error and I'm using the latest version of harbor v1.10.1.

**Comment by c4po** [comment]
@Pruthvi08 can you share the full logs through git gist?

**Comment by pruthvirajkanmantha** [comment]
[harbor_exporter_logs.txt](https://github.com/c4po/harbor_exporter/files/4345623/harbor_exporter_logs.txt)

**Comment by c4po** [comment]
@Pruthvi08 can you check if the user have permission to access the api  `/api/quotas` ? it seems the exporter cannot get repo_id from the result.

**Comment by pruthvirajkanmantha** [comment]
@c4po I'm using admin super user to scarpe the metrics. I tried sending a GET to /api/quotas manually and got response with all the quota sizes of various repositories. 
For ref:
`  {
    "id": 1,
    "ref": null,
    "creation_time": "2020-02-26T15:56:50.244519Z",
    "update_time": "2020-02-26T15:56:50.244519Z",
    "hard": {
      "count": -1,
      "storage": -1
    },
    "used": {
      "count": 0,
      "storage": 0
    }
  }`

**Comment by c4po** [comment]
@Pruthvi08  what I got on my harbor server is a list of quota object like ` [ {"id":1,...}]`. So you only got a single json object not a list? If it's the case, I think that's the issue. The code is try to parser the vault from a json list.

**Comment by pruthvirajkanmantha** [comment]
@c4po  I actually got a list. But i only posted a part of it.

**Comment by c4po** [comment]
@Pruthvi08 can you post the full list? I cannot reproduce the error in my setup.

**Comment by pruthvirajkanmantha** [comment]
@c4po 
[quotas.txt](https://github.com/c4po/harbor_exporter/files/4360743/quotas.txt)

And the log message:
level=error ts=2020-03-20T13:30:28.256Z caller=harbor_exporter.go:111 msg="error gathering metrics:8 error(s) occurred:\n* collected metric \"harbor_quotas_count_total\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"hard\" > gauge:<value:-1 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_count_total\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"used\" > gauge:<value:0 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_size_bytes\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"hard\" > gauge:<value:2.199023255552e+12 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_size_bytes\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"used\" > gauge:<value:0 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_count_total\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"hard\" > gauge:<value:-1 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_count_total\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"used\" > gauge:<value:0 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_size_bytes\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"hard\" > gauge:<value:-1 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_size_bytes\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"used\" > gauge:<value:0 > } was collected before with the same name and label values"

Thanks in advance !!!

**Comment by c4po** [comment]
@Pruthvi08  do you know why you get `"ref": null, ` in your quota response json? it should be the repo name and repo id.
however, I made a fix to handle this edge case. please test with the new image `c4po/harbor-exporter:v0.3-debug` and let me know if the error message is gone

**Comment by c4po** [comment]
@Pruthvi08 do you have a chance to test this out?

**Comment by pruthvirajkanmantha** [comment]
@c4po  Sorry for the delay. I tried using the new image c4po/harbor-exporter:v0.3-debug. I know don't see the issue with the duplication of metrics anymore. But i also noticed that i have a different issue which i have mentioned as an attachment.  
<img width="1436" alt="Screenshot 2020-03-29 at 17 42 49" src="https://user-images.githubusercontent.com/16479314/77853587-157a2f80-71e5-11ea-898f-308f54e97f4f.png">

<img width="1436" alt="Screenshot 2020-03-29 at 17 42 12" src="https://user-images.githubusercontent.com/16479314/77853558-efed2600-71e4-11ea-8438-429de78c6ece.png">

![Uploading Screenshot 2020-03-29 at 17.42.49.png…]()
<img width="1436" alt="Screenshot 2020-03-29 at 17 43 26" src="https://user-images.githubusercontent.com/16479314/77853610-2e82e080-71e5-11ea-953b-793a57f8fbd2.png">

**Comment by c4po** [comment]
@Pruthvi08 is this an issue with your prometheus setup? do you have this with harbor exporter only?

**Comment by pruthvirajkanmantha** [comment]
Thanks @c4po . The issue seems to be in prometheus config, the default scrape_timeout was set to 10 sec. In case of harbor-exporter sometimes it takes more than 10 sec to get the metrics and the empty spaces in the graph are basically because of that. The issue seems to be resolved now. Please close the issue.
