### ISSUE TITLE
"422 Unprocessable Entity" error when scraping "/projects?page=1&page_size=500" with default HARBOR_PAGESIZE (500)

### ISSUE THREAD

**Issue by dkulchinsky** [c4po/harbor_exporter#56]
Hey folks,

Been testing the latest version with pagination on a Harbor v2.1.0 deployment and with the default `HARBOR_PAGESIZE=500`, we're getting the following error:

```
level=error ts=2020-10-05T13:12:30.165Z caller=harbor_exporter.go:249 msg="Error handling request for /projects?page=1&page_size=500" http-statuscode="422 Unprocessable Entity"
level=error ts=2020-10-05T13:12:30.165Z caller=metrics_repositories.go:64 unexpectedendofJSONinput=(MISSING)
```

adjusting `HARBOR_PAGESIZE` to `100` "fixes" the issue.

as far as I can tell, the API does support a max of 500: https://github.com/goharbor/harbor/blob/58b7242a2551205428584b24bf11f1fd7d2b69fd/src/common/api/base.go#L32-L33

but any value >100 results in above error and missing repositories metrics (it appears only `/projects` endpoint is affected).

the API swagger does indeed suggest the max is 100: 
https://github.com/goharbor/harbor/blob/5293c8ff4b6778cd79cda156dff994929517a674/api/v2.0/swagger.yaml#L1499-L1507

/cc @c4po 
/cc @xtreme-conor-nosal

**Comment by cjnosal** [comment]
I haven't seen the 422 specifically but did see gateway timeouts with large page sizes (even though the result set was < 100...). I think a default in the 50-100 range would be a good middle ground between small harbors not needing paging and leaving the tuning of larger deployments to the operator.

**Comment by dkulchinsky** [comment]
Thanks @xtreme-conor-nosal! I'm curious if it's Harbor version dependant, which Harbor version do you run? and I agree, a default of 100 sounds like a good starting point and then folks can adjust as needed.

**Comment by cjnosal** [comment]
We're still running Harbor 2.0.x, though our data sets aren't approaching 500 of anything yet, and my PR and testing used smaller page sizes. 

I'm not sure how to reconcile the 500 in harbor code with the 100 in the swagger docs - it's worth clarifying with the Harbor developers. One other thought I had is if you check your Harbor logs does the `core` return 422 to `nginx`, or does only `nginx` log the 422? (i.e. does the microservice handle requests for 500, but something in the nginx configuration interferes? - but maybe I'm thinking of `HTTP 413`)
