### ISSUE TITLE
artifacts collector fails when there are repos without artifacts

### ISSUE THREAD

**Issue by dkulchinsky** [c4po/harbor_exporter#75]
Hey folks 👋🏼 

Just upgraded to 0.6.0 and very excited about the new artifacts collector, however it seems it has a small issue where it doesn't handle the situation when repositories have no artifacts/images:

```
level=error ts=2021-01-26T14:41:24.282Z caller=harbor_exporter.go:263 msg="Error handling request for /projects/dockerhub/repositories/library/vault/artifacts?with_tag=true&with_scan_overview=true&page=1&page_size=100" http-statuscode="404 Not Found"
level=error ts=2021-01-26T14:41:24.282Z caller=metric_artifacts.go:296 unexpectedendofJSONinput=(MISSING)
level=error ts=2021-01-26T14:41:24.282Z caller=metric_artifacts.go:217 unexpectedendofJSONinput=(MISSING)
```

above is a proxy cache project with a bunch of repositories where images were deleted by the default retention rule (although we have similar conditions in non proxy cache projects).

I haven't looked at the code, but I suppose it doesn't account for the possibility where a repo might not have any artifacts/images.

I'll take a look at the code, see if I can spot anything obvious.

/cc @ErmakovDmitriy, @c4po

**Comment by dkulchinsky** [comment]
after looking at this some more I believe my initial conclusion was wrong, the issue seems to be when the repository name includes a `/`, according to the API docs:

```
repository_name *string(path) | The name of the repository. If it contains slash, encode it with URL encoding. e.g. a/b -> a%252Fb
```

**Comment by ErmakovDmitriy** [comment]
Hi @dkulchinsky,
Thank you for your pull request!
