### ISSUE TITLE
include the tag name in the artifacts_* metrics

### ISSUE THREAD

**Issue by dkulchinsky** [c4po/harbor_exporter#77]
Happy to see the new artifacts_* metrics, great stuff 👍🏼 

I was wondering if it would be worth adding the tag name as a label? the artifact_name includes the artifact's digest but tags are more human readable I'd say.

Thoughts?

**Comment by warroyo** [comment]
I am looking into submitting a PR for this. I think one challenge is handling multiple tags on an image. thoughts on how you would like to see that happen are appreciated

**Comment by warroyo** [comment]
ok so I decided initially to do this by producing a metric for every tag. there is obviously duplication if you have multiple tags by filtering this out should be really easy with promql PR coming soon

**Comment by warroyo** [comment]
PR https://github.com/c4po/harbor_exporter/pull/80
