### ISSUE TITLE
can't scrape metrics from harbor-exporter, it looks like timeout, not response.

### ISSUE THREAD

**Issue by zhongguanqun** [c4po/harbor_exporter#92]
run log:
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:447 CacheEnabled=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:448 CacheDuration=20s
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:450 msg="Starting harbor_exporter" version="(version=v0.6.4, branch=master, revision=052f98a8fabafcfc116b359914da1f978b10203d)"
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:451 build_context="(go=go1.13.15, user=root, date=2021-03-23-15:28:44-UTC)"
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=repositories collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=replication collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=systeminfo collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=artifacts collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=health collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=scans collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=statistics collect=true
level=info ts=2021-04-01T04:33:57.757Z caller=harbor_exporter.go:462 metrics_group=quotas collect=true
level=info ts=2021-04-01T04:33:57.770Z caller=harbor_exporter.go:280 msg="check v1 with /api/systeminfo" code=404
level=info ts=2021-04-01T04:33:57.860Z caller=harbor_exporter.go:291 msg="check v2 with /api/v2.0/systeminfo" code=200
level=info ts=2021-04-01T04:33:57.860Z caller=harbor_exporter.go:500 msg="Listening on address" address=:9107

prometheus error:
context deadline exceeded

harbor version:2.1.4

**Comment by Nick-Triller** [comment]
Hi @zhongguanqun,
what do you observe when you send a request to `/metrics` manually?
```bash
time curl $URL:$PORT/metrics
```
