### ISSUE TITLE
Collect metrics periodically instead of on scrape

### ISSUE THREAD

**Issue by Nick-Triller** [c4po/harbor_exporter#93]
Hi,

collecting metrics takes a long time for Harbor installations with a large amount of content. We are at a point where Prometheus scrapes time out when the exporter invalidates the cached metrics because collecting the metrics takes too long. This might be the problem in #92, too.

I propose implementing continuous, periodic metrics collection that is independent from scrape requests. Scrapes receive the last set of collected metrics. This way scrape requests can be responded to quickly at all times. Additionally, load on Harbor can be reduced because metrics collection doesn't have to happen as fast as possible anymore.

@c4po I am happy to implement this solution if it's a contribution you will accept.

Best
Nick

**Comment by c4po** [comment]
for large prometheus metrics collection, I think we should increase the scrape_interval instead of let the exporter decide when to collect the data.
prometheus exporter should just be a proxy layer between prometheus and application to reorg the data.

**Comment by Nick-Triller** [comment]
Hi @c4po,
thank you for your timely feedback. I see your standpoint, I will disable expensive collectors instead of making the exporter more complex.
Best, Nick

**Comment by kiefersmith** [comment]
I am also having a similar issue.  Harbor's scrape consistently hits > 10s.  Going to increase the `scrape_timeout` for the job, but I'm not convinced it's a permanent solution.

**Comment by Nick-Triller** [comment]
@kiefersmith consider disabling artifact metrics with `--skip.metrics artifacts` if you haven't yet. Scrape duration fell from 1:40min to 2s for us.

**Comment by kiefersmith** [comment]
@Nick-Triller Yeah, that's a good recommendation, thanks.  We're not running the latest version of  Harbor (comes with metrics!) yet, so might also look at supplementing with those when we upgrade.

If I remember I'll report back with my findings.  👍🏻
