### ISSUE TITLE
Volume Metrics are not Generated

### ISSUE THREAD

**Issue by hemantdindi** [c4po/harbor_exporter#97]
When We ran the exporter, came across the below error -
```shell
level=info ts=2021-06-14T16:48:42.261Z caller=harbor_exporter.go:175 msg="check v1 with /api/systeminfo" code=404
level=info ts=2021-06-14T16:48:42.307Z caller=harbor_exporter.go:186 msg="check v2 with /api/v2.0/systeminfo" code=200
level=info ts=2021-06-14T16:48:42.308Z caller=harbor_exporter.go:302 msg="Listening on address" address=:9107
level=error ts=2021-06-14T16:49:44.161Z caller=metrics_systemvolumes.go:19 json:cannotunmarshalarrayintoGostructfieldsystemVolumesMetric.Storageoftypestruct{Totalfloat64;Freefloat64}=(MISSING)
```

**Comment by brtkwr** [comment]
Same here

**Comment by gorkemozlu** [comment]
same here. it might be related with harbor version. it's v2.2.1 for us.

**Comment by gorkemozlu** [comment]
ping.

**Comment by TomHellier** [comment]
hi is anyone looking at this?

**Comment by el1x1r** [comment]
Same here, any update on this?

**Comment by jayolmos** [comment]
ping

**Comment by TomHellier** [comment]
@jayolmos I migrated to use goharbor/harbor-exporter.

**Comment by timdittler** [comment]
Thanks for the hint @TomHellier. Does it also export `harbor_artifacts_vulnerabilities`? I can only find [this doc](https://goharbor.io/docs/2.2.0/administration/metrics/), so I guess not?!

**Comment by SilenceAdele** [comment]
To solve this problem, you need to use the code of this patch [Support harbor v2.6](https://github.com/c4po/harbor_exporter/commit/8d7e27a6caf794dd195137c8c44c5f7479befdf2).By the way, the image provided by the community is not the latest code, you need to create the image by yourself.
